window.MAP_GUIDES = [
  {
    slug: "astra-malorum",
    trackerKey: "astra_malorum",
    title: "Astra Malorum",
    cardLabel: "Easter Egg Guide",
    image: "astra-malorum-easter-egg-guide.jpg",
    lastUpdated: "April 2026",
    featured: false,
    searchTerms: "black ops zombies easter egg ritual relic altar boss fight",
    notes: "Coming Soon!.",
    quickNotes: ["Coming Soon!."],
    steps: [
      "Step 1 — Find 2 Telescope (Harmonic Oculus) components. (1st - Luminarium, 2nd - Machina Astralis)."
      "Step 2 — 
    ]
  },
  {
    slug: "ashes-of-the-damned",
    trackerKey: "ashes_of_the_damned",
    title: "Ashes of the Damned",
    cardLabel: "Easter Egg Guide",
    image: "ashes-of-the-damned-easter-egg-guide.jpg",
    lastUpdated: "April 2026",
    featured: false,
    searchTerms: "black ops zombies easter egg crypt skull cursed key fire pillars final encounter",
    notes: "Coming Soon!.",
    quickNotes: ["Coming Soon!."],
    steps: [
      "Steps Coming Soon!."
    ]
  },
  {
    slug: "paradox-junction",
    trackerKey: "paradox_junction",
    title: "Paradox Junction",
    cardLabel: "Easter Egg Guide",
    image: "paradox-junction-easter-egg-guide.jpg",
    lastUpdated: "April 2026",
    featured: true,
    searchTerms: "black ops zombies newest featured blundergat sundergat pack a punch boss guide",
    notes: "For Boss: Fireplace: Trinity Ave., Toy Box: Green house backyard, Piano: Yellow house background.",
    quickNotes: [
      "Always save 1 zombie before ending the round to complete steps easier.",
      "Recommended Explosive = Ray Gun / Semtex.",
      "Take note of humming Cyst, Mannequin, & wall no later than round 5.",
      "Humming sounds have a chance to spawn on the other side of the truck.",
      "Need Death Perception, Tomahawk, Molatov."
    ],
    steps: [
      "Step 1 — Present: Find cyst with humming sound.",
      "Step 2 — Present: Grab keys from back of yellow garage.",
      "Step 3 — Present: Go upstairs of yellow house and grab the vial on the desk.",
      "Step 4 — Present: Interact with sink in green house and fill vial with acid.",
      "Step 5 — Present: Find mannequin with humming sound and take note of it.",
      "Step 6 — Present: Find humming wall (Possible locations, Inside yellow garage, Top stairs in green house, By perk machine).",
      "Step 7 — Present: Clear dog round.",
      "Step 8 — Past: Move truck with keys.",
      "Step 9 — Past: Shoot 4 riffs to get Pack-A-Punch.",
      "Step 10 — Past: Go to bedroom of yellow house and interact with cabinet to get sealant.",
      "Step 11 — Past: Shoot swing seat in back of yellow house and pick up seat.",
      "Step 12 — Past: Put acid on mannequin head that was located in the present.",
      "Step 13 — Past: Throw explosive at humming wall.",
      "Step 14 — Present: Find mannequin and pick up part.",
      "Step 15 — Present: Build crafting table in bus to get Blundergat.",
      "Step 16 — Present: Place swing seat back on swing in back of yellow house.",
      "Step 17 — Present: Find RC controller (Possible locations, Back of map right of brown box, Yellow garage bottom shelf, Green backyard behind fence).",
      "Step 18 — Present: With RC car jump ramp over fence and explode barrel next to garage door.",
      "Step 19 — Present: Go to open garage just after the truck, pick up head on safe, then pick up chalk.",
      "Step 20 — Present: Kill 3 fire tornado zombies with Blundergat, Bring zombie to crafting table and do not let zombies connect. Total is 3 zombies, kill 1 per round. (Possible spawn locations, Yellow backyard, Green backyard, By perk machine. Last one is mimic).",
      "Step 21 — Past: Use crafting table, melee and place Blundergat.",
      "Step 22 — Present: Get upgraded Blundergat (Sundergat).",
      "Step 23 — Present: Go to swing in back of yellow house and place chalk. (Need Death Perception).",
      "Step 24 — Present: Go to siren, left of Pack-A-Punch and hit with explosive. Goggles will drop. (Make the wisp appear and retrieve them by killing zombies).",
      "Step 25 — Present: Find headset (Possible locations corner of fence left of gobblegum machine, upstairs green house in dark, or back yellow right corner by perk).",
      "Step 26 — Present: Pick up seeds in red box in yellow garage.",
      "Step 27 — Past: Open toy box and place items.",
      "Step 28— Past: Place seeds to plant tree left of Pack-A-Punch and kill with Sundergat until white screen appears. (Get Tomahawk).",
      "Step 29 — Present: Use tomahawk to get 3 pieces of wood from tree by Pack-A-Punch.",
      "Step 30 — Past: Place wood in chimney of yellow house. (Need Molotov).",
      "Step 31 — Past: Throw Molotov at firewood to start fire in chimney.",
      "Step 32 — Present: Fire should be green. Go to driveway by perk machine, Step on X to start hopscotch. (Glow should be blue).",
      "Step 33 — Past: Pass hopscotch. (Jump 1 to 12 then 12 to 1. Do not hit lines or black spot)",
      "Step 34 — Past: Get kills with Sundergat to move music box to fireplace.",
      "Step 35 — Past: Find ball and shoot it with Sundergat to the X behind the green house. (Possible locations, Backyard at top of yellow house rooftop area, Rooftop just around the truck, Top of crates by perk machine).",
      "Step 36 — Past: Pass 4-square. (Move ball with melee to a different square until white screen).",
      "Step 37 — Past: Get kills with Sundergat to move music box to toy box. (Need Psyche Grenade)",
      "Step 38 — Present: Go to backyard of green house and find Piano Teacher. (Spawns near the end of the round and hit with a psyche Grenade).",
      "Step 39 — Present: Go to past. (Piano Teacher should explode at the piano).",
      "Step 40 — Present: Go to present, Collect 8 symbols based on blinks from 1 to 8. (Possible locations, Back of fence in yellow backyard, Yellow bus, Garage by perk machine, wall just around the truck, Side of bunker in green house backyard, Rock next to pack a punch, Front of truck on burning house, In corner on fence by teleporter).",
      "Step 41 — Past: Interact with piano using 86756535.",
      "Step 42 — Present: Find floating zombies outside of green house backyard and shoot 3 then Go to X by truck.",
      "Step 43 — Past: Pass Jax (Kill zombies in air before ball touches ground. Do not shoot the ball).",
      "Step 44 — Past: Get kills with Sundergat to move music box to piano",
      "Step 45 — Present: Get on top of bus with crafting table. Set red and white hand of clock to 0. Shoot red hand right before teleporting. (If timed correctly, you will spawn in the past).",
      "Step 46 — Past: Go to piano in green house the twins should be there. Twins will transform into an orb to 1st the toy box, 2nd yellow house in front of fire place, 3rd backyard yellow swings revealing a yellow ord to start boss fight.",
      "Step 47 — Past: Be ready for boss. Interact with swings to start boss fight",
      "Step 48 — Boss: Go to each area and shoot cysts. (Fireplace: Trinity Ave., Toy Box: Green house backyard, Piano: Yellow house background",
      "Step 49 — Boss: Defend each field in each area.",
      "Step 50 — Boss: Fight boss (Shoot bright spots).",
      "Step 51 — Boss: Repeat Pack-A-Punch phase and kill zombies from orbs.",
      "Step 52 — Boss: Bring tortured zombie to black mass, then kill tortured zombie .",
      "Step 53 — Boss: Keep repeating the cycle.",
      "Step 54 — Boss: Charge and repeat. Hit glowing spots."
    ]
  }
];
